


UPDATE_BORDER_BUFFER_GAME:
	CALL	UPDATE_BORDER_BUFFER_FISH
	CALL	UPDATE_BORDER_BUFFER_SCORE
	CALL	UPDATE_BORDER_BUFFER_HEALTH
	RET 				; UPDATE_BORDER_BUFFER


BORDER_BUFFER_SCORE:
	DEFB	%00000000	; BCD 0-0 

	; colours from font


BORDER_BUFFER_SCORE_INC:
	LD 		A, (BORDER_BUFFER_SCORE)     

	; check max
	CP 		%10011001
	JP	 	NZ, BORDER_BUFFER_SCORE_INC_INC

	; at max, so 0 again
	LD 		A, 0
	JP 		BORDER_BUFFER_SCORE_INC_SAVE

BORDER_BUFFER_SCORE_INC_INC:
	; inc
	ADD 	A, 1        ; ADD not INC for correct flags
    DAA                 ; BCD adjust

BORDER_BUFFER_SCORE_INC_SAVE:
    LD 		(BORDER_BUFFER_SCORE), A

	RET 				; BORDER_BUFFER_SCORE_INC

UPDATE_BORDER_BUFFER_SCORE:
	; left
	LD 		A, (BORDER_BUFFER_SCORE)
	AND 	%11110000	; left BCD
	SRL 	A
	SRL 	A
	SRL 	A			; shifted so it's double actual number

	LD 		D, 0
	LD 		E, A 		; DE is offset for LUT

	LD 		HL, SB_BORDER_FONT_LUT_LEFT
	ADD 	HL, DE		; (hl) points to font
	LD 		DE, (HL)
	LD 		HL, DE

	; copy font to buffer
	LD 		DE, TOP_BORDER_BUFFER_GAME + 2	; start of left number

	LD 		B, 8			; 8 lots of 7 rows
UPDATE_BORDER_BUFFER_SCORE_OUTER_LOOP:
	PUSH 	BC
	; 7 rows of 3 pixels
	LD 		B, 7
UPDATE_BORDER_BUFFER_SCORE_INNER_LOOP:
	PUSH 	HL

	LDI 
	LDI 
	LDI 

	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE				; skip 8 to next row

	POP		HL
	DJNZ 	UPDATE_BORDER_BUFFER_SCORE_INNER_LOOP

	INC		HL
	INC		HL
	INC		HL				; move to new font row

	POP 	BC
	DJNZ 	UPDATE_BORDER_BUFFER_SCORE_OUTER_LOOP

	; right
	LD 		A, (BORDER_BUFFER_SCORE)
	AND 	%00001111		; right BCD
	SLA		A

	LD 		D, 0
	LD 		E, A 			; DE is offset for LUT

	LD 		HL, SB_BORDER_FONT_LUT_RIGHT
	ADD 	HL, DE			; (hl) point to font
	LD 		DE, (HL)
	LD 		HL, DE

	; copy font to buffer
	LD 		DE, TOP_BORDER_BUFFER_GAME + 6	; start of right number

	LD 		B, 8			; 8 lots of 7 rows
UPDATE_BORDER_BUFFER_SCORE_OUTER_LOOP_R:
	PUSH 	BC
	; 7 rows of 3 pixels
	LD 		B, 7
UPDATE_BORDER_BUFFER_SCORE_INNER_LOOP_R:
	PUSH 	HL

	LDI 
	LDI 
	LDI 

	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE
	INC 	DE				; skip 8 to next row

	POP		HL
	DJNZ 	UPDATE_BORDER_BUFFER_SCORE_INNER_LOOP_R

	INC		HL
	INC		HL
	INC		HL				; move to new font row

	POP 	BC
	DJNZ 	UPDATE_BORDER_BUFFER_SCORE_OUTER_LOOP_R

	RET 				; UPDATE_BOARDER_BUFFER_SCORE

; health
BORDER_BUFFER_HEALTH:
	DEFB	112			; 56 * 2 for cheating double attr hits...

BORDER_BUFFER_HEALTH_INC:
	LD		A, (BORDER_BUFFER_HEALTH)
	CP 		112
	RET 	NC			; already 56 or bigger, don't INC

	INC 	A
	LD 		(BORDER_BUFFER_HEALTH), A

	RET 				; BORDER_BUFFER_HEALTH_INC

BORDER_BUFFER_HEALTH_DEC:
	LD		A, (BORDER_BUFFER_HEALTH)
	CP 		0
	RET 	Z			; already 0, don't DEC

	DEC 	A
	LD 		(BORDER_BUFFER_HEALTH), A
	RET 				; BORDER_BUFFER_HEALTH_DEC

BORDER_BUFFER_HEALTH_BG_COL:
	DEFB	COL_MAG

BORDER_BUFFER_HEALTH_COL:
	DEFB	COL_RED

UPDATE_BORDER_BUFFER_HEALTH:
	LD 		DE, 11			; 11 per row
	LD 		HL, TOP_BORDER_BUFFER_GAME + 10
							; points to HEALTH bar

	; 56 - (BORDER_BUFFER_HEALTH) : rows of bg
	LD 		A, (BORDER_BUFFER_HEALTH)
	SRA 	A 				; divide by 2 for attr dmg cheat 

	LD  	B, A
	LD 		A, 56
	SUB		B				; A now has how many rows of bg
	JP 		Z, HEALTH_ON	; HEALTH is 56 full, no bg colour needed

	LD 		B, A
	LD 		A, (BORDER_BUFFER_HEALTH_BG_COL)
HEALTH_OFF_LOOP:
	LD 	 	(HL), A
	ADD 	HL, DE
	DJNZ 	HEALTH_OFF_LOOP

HEALTH_ON:
	; (BORDER_BUFFER_HEALTH) - 42 : rows of hi (max 14)
	LD 		A, (BORDER_BUFFER_HEALTH)
	SRA 	A 				; divide by 2 for attr dmg cheat 
	JP   	C, HEALTH_DONE	; negative so no hi
	JP      Z, HEALTH_DONE	; 0 so no high

	LD		B, A 
	LD 		A, (BORDER_BUFFER_HEALTH_COL)
HEALTH_ON_LOOP:
	LD 	 	(HL), A
	ADD 	HL, DE
	DJNZ 	HEALTH_ON_LOOP

HEALTH_DONE:
	RET					; UPDATE_BORDER_BUFFER_HEALTH

; fish
BORDER_BUFFER_FISH:
	DEFB	0			; max 56 * 2 for cheating double attr hits...

BORDER_BUFFER_FISH_INC:
	LD		A, (BORDER_BUFFER_FISH)
	CP 		112
	RET 	NC			; already 56 or bigger, don't INC

	ADD 	A, 8
	LD 		(BORDER_BUFFER_FISH), A

	RET 				; BORDER_BUFFER_FISH_INC

BORDER_BUFFER_FISH_BG_COL:
	DEFB	COL_GRN

BORDER_BUFFER_FISH_COL:
	DEFB	COL_YEL

UPDATE_BORDER_BUFFER_FISH:
	LD 		DE, 11			; 11 per row
	LD 		HL, TOP_BORDER_BUFFER_GAME
							; points to FISH bar

	; 56 - (BORDER_BUFFER_FISH) : rows of bg
	LD 		A, (BORDER_BUFFER_FISH)
	SRA 	A 				; divide by 2 for attr dmg cheat 

	LD  	B, A
	LD 		A, 56
	SUB		B				; A now has how many rows of bg
	JP 		Z, FISH_ON	; HEALTH is 56 full, no bg colour needed

	LD 		B, A
	LD 		A, (BORDER_BUFFER_FISH_BG_COL)
FISH_OFF_LOOP:
	LD 	 	(HL), A
	ADD 	HL, DE
	DJNZ 	FISH_OFF_LOOP

FISH_ON:
	; (BORDER_BUFFER_HEALTH) - 42 : rows of hi (max 14)
	LD 		A, (BORDER_BUFFER_FISH)
	SRA 	A 				; divide by 2 for attr dmg cheat 
	JP   	C, FISH_DONE	; negative so no hi
	JP      Z, FISH_DONE	; 0 so no high

	LD		B, A 
	LD 		A, (BORDER_BUFFER_FISH_COL)
FISH_ON_LOOP:
	LD 	 	(HL), A
	ADD 	HL, DE
	DJNZ 	FISH_ON_LOOP

FISH_DONE:
	RET					; UPDATE_BORDER_BUFFER_FISH

; 56 x 11
TOP_BORDER_BUFFER_GAME:
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN

	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN

	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN

	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN

	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN

	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
	DEFB 	COL_GRN, COL_GRN, COL_GRN, COL_GRN, COL_BLU, COL_BLU, COL_BLU, COL_GRN, COL_GRN, COL_GRN, COL_GRN
